############### Server ###############
server:
  port: 8080

###############  DB  ###############
spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    hikari:
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
    open-in-view: false

###############  Logging  ###############
logging:
  level:
    root: debug

###############  JWT  ###############
jwt:
  secret: c3ByaW5nLWJvb3Qtc3pzLXByb2plY3QtdG9rZW4tc2VjcmV0LWtleS1pbmZvLWp3dC1tYWluLWtleXNwcmluZy1ib290LXN6cy1wcm9qZWN0LXRva2VuLXNlY3JldC1rZXktaW5mby1qd3QtbWFpbi1rZXk=
  expiration_time: 86400

###############  AES128  ###############
aes:
#  SZS-AES128 base64
  secret: U1pTLUFFUzEyOA==
